# -*- coding: utf-8 -*-
"""NYU_DATA_SCIENCE_BOOTCAMP_WEEK1_Take_Home_Exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1epSnfmfglepAO0EOzitL_II5-MSLzlQ8

##1. Write a function count_vowels(word) that takes a word as an argument and returns the number of vowels in the word
"""

def vowels():
    word = input("Word: ")
    i = 0
    for vowel in word:
        if vowel in ("a" "e" "i" "o" "u" "A" "E" "I" "O" "U"):
            i += 1
    return i

print("Number of vowels:", vowels())

"""##2. Iterate through the following list of animals and print each one in all caps.
animals=['tiger', 'elephant', 'monkey', 'zebra', 'panther']
"""

animals=['tiger', 'elephant', 'monkey', 'zebra', 'panther']
for i in animals:
  print(i.upper())

"""##3. Write a program that iterates from 1 to 20, printing each number and whether it's odd or even."""

for i in range(1, 21):
  if i%2 == 1:
    print(i, ": The number is odd")
  else:
    print(i, ": The number is even")

"""##4. Write a function sum_of_integers(a, b) that takes two integers as input from the user and returns their sum."""

a = input("enter a: ")
b = input("enter b: ")

sum = float(a)+float(b)

print("sum:", sum)